/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package principal;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Diego
 */
public class interfaz extends javax.swing.JFrame {

    int columnas=10;
    int filas=10;
    public interfaz() {
        initComponents();
        GridLayout gridLayout = new GridLayout(filas, columnas);
        
        panel_matrizE1.setLayout(gridLayout);
        asignar(panel_matrizE1);
        panel_matrizE2.setLayout(gridLayout);
        asignar(panel_matrizE2);
        panel_matrizE3.setLayout(gridLayout);
        asignar(panel_matrizE3);
        panel_matrizE4.setLayout(gridLayout);
        asignar(panel_matrizE4);
        
        panel_matrizP1.setLayout(gridLayout);
        asignar(panel_matrizP1);
        panel_matrizP2.setLayout(gridLayout);
        asignar(panel_matrizP2);
        panel_matrizP3.setLayout(gridLayout);
        asignar(panel_matrizP3);
        panel_matrizP4.setLayout(gridLayout);
        asignar(panel_matrizP4);

        panel_matrizMax1.setLayout(gridLayout);
        panel_matrizMax1.setBackground(Color.WHITE);
        panel_matrizMax2.setLayout(gridLayout);
        panel_matrizMax2.setBackground(Color.WHITE);
        panel_matrizMax3.setLayout(gridLayout);
        panel_matrizMax3.setBackground(Color.WHITE);
        panel_matrizMax4.setLayout(gridLayout);
        panel_matrizMax4.setBackground(Color.WHITE);
        
        panel_matrizMin1.setLayout(gridLayout);
        panel_matrizMin1.setBackground(Color.WHITE);
        panel_matrizMin2.setLayout(gridLayout);
        panel_matrizMin2.setBackground(Color.WHITE);
        panel_matrizMin3.setLayout(gridLayout);
        panel_matrizMin3.setBackground(Color.WHITE);
        panel_matrizMin4.setLayout(gridLayout);
        panel_matrizMin4.setBackground(Color.WHITE);
    }//

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel_matrizE1 = new javax.swing.JPanel();
        panel_matrizE2 = new javax.swing.JPanel();
        panel_matrizE4 = new javax.swing.JPanel();
        panel_matrizE3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel_matrizP2 = new javax.swing.JPanel();
        panel_matrizP4 = new javax.swing.JPanel();
        panel_matrizP3 = new javax.swing.JPanel();
        panel_matrizP1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panel_matrizMax1 = new javax.swing.JPanel();
        panel_matrizMax2 = new javax.swing.JPanel();
        panel_matrizMax4 = new javax.swing.JPanel();
        panel_matrizMax3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panel_matrizMin1 = new javax.swing.JPanel();
        panel_matrizMin3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panel_matrizMin4 = new javax.swing.JPanel();
        panel_matrizMin2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        panel_matrizE1.setPreferredSize(new java.awt.Dimension(150, 150));
        panel_matrizE1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_matrizE1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout panel_matrizE1Layout = new javax.swing.GroupLayout(panel_matrizE1);
        panel_matrizE1.setLayout(panel_matrizE1Layout);
        panel_matrizE1Layout.setHorizontalGroup(
            panel_matrizE1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_matrizE1Layout.setVerticalGroup(
            panel_matrizE1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        panel_matrizE2.setPreferredSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout panel_matrizE2Layout = new javax.swing.GroupLayout(panel_matrizE2);
        panel_matrizE2.setLayout(panel_matrizE2Layout);
        panel_matrizE2Layout.setHorizontalGroup(
            panel_matrizE2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_matrizE2Layout.setVerticalGroup(
            panel_matrizE2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        panel_matrizE4.setPreferredSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout panel_matrizE4Layout = new javax.swing.GroupLayout(panel_matrizE4);
        panel_matrizE4.setLayout(panel_matrizE4Layout);
        panel_matrizE4Layout.setHorizontalGroup(
            panel_matrizE4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 162, Short.MAX_VALUE)
        );
        panel_matrizE4Layout.setVerticalGroup(
            panel_matrizE4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        panel_matrizE3.setPreferredSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout panel_matrizE3Layout = new javax.swing.GroupLayout(panel_matrizE3);
        panel_matrizE3.setLayout(panel_matrizE3Layout);
        panel_matrizE3Layout.setHorizontalGroup(
            panel_matrizE3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_matrizE3Layout.setVerticalGroup(
            panel_matrizE3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jLabel1.setText("Entrenamiento");

        panel_matrizP2.setPreferredSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout panel_matrizP2Layout = new javax.swing.GroupLayout(panel_matrizP2);
        panel_matrizP2.setLayout(panel_matrizP2Layout);
        panel_matrizP2Layout.setHorizontalGroup(
            panel_matrizP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_matrizP2Layout.setVerticalGroup(
            panel_matrizP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        panel_matrizP4.setPreferredSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout panel_matrizP4Layout = new javax.swing.GroupLayout(panel_matrizP4);
        panel_matrizP4.setLayout(panel_matrizP4Layout);
        panel_matrizP4Layout.setHorizontalGroup(
            panel_matrizP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 162, Short.MAX_VALUE)
        );
        panel_matrizP4Layout.setVerticalGroup(
            panel_matrizP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        panel_matrizP3.setPreferredSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout panel_matrizP3Layout = new javax.swing.GroupLayout(panel_matrizP3);
        panel_matrizP3.setLayout(panel_matrizP3Layout);
        panel_matrizP3Layout.setHorizontalGroup(
            panel_matrizP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_matrizP3Layout.setVerticalGroup(
            panel_matrizP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        panel_matrizP1.setPreferredSize(new java.awt.Dimension(150, 150));
        panel_matrizP1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_matrizP1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout panel_matrizP1Layout = new javax.swing.GroupLayout(panel_matrizP1);
        panel_matrizP1.setLayout(panel_matrizP1Layout);
        panel_matrizP1Layout.setHorizontalGroup(
            panel_matrizP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_matrizP1Layout.setVerticalGroup(
            panel_matrizP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jLabel2.setText("PRUEBA");

        panel_matrizMax1.setPreferredSize(new java.awt.Dimension(150, 150));
        panel_matrizMax1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_matrizMax1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout panel_matrizMax1Layout = new javax.swing.GroupLayout(panel_matrizMax1);
        panel_matrizMax1.setLayout(panel_matrizMax1Layout);
        panel_matrizMax1Layout.setHorizontalGroup(
            panel_matrizMax1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_matrizMax1Layout.setVerticalGroup(
            panel_matrizMax1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        panel_matrizMax2.setPreferredSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout panel_matrizMax2Layout = new javax.swing.GroupLayout(panel_matrizMax2);
        panel_matrizMax2.setLayout(panel_matrizMax2Layout);
        panel_matrizMax2Layout.setHorizontalGroup(
            panel_matrizMax2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_matrizMax2Layout.setVerticalGroup(
            panel_matrizMax2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        panel_matrizMax4.setPreferredSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout panel_matrizMax4Layout = new javax.swing.GroupLayout(panel_matrizMax4);
        panel_matrizMax4.setLayout(panel_matrizMax4Layout);
        panel_matrizMax4Layout.setHorizontalGroup(
            panel_matrizMax4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_matrizMax4Layout.setVerticalGroup(
            panel_matrizMax4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        panel_matrizMax3.setPreferredSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout panel_matrizMax3Layout = new javax.swing.GroupLayout(panel_matrizMax3);
        panel_matrizMax3.setLayout(panel_matrizMax3Layout);
        panel_matrizMax3Layout.setHorizontalGroup(
            panel_matrizMax3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 162, Short.MAX_VALUE)
        );
        panel_matrizMax3Layout.setVerticalGroup(
            panel_matrizMax3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jLabel3.setText("RECUPERADO MAXIMOS");

        panel_matrizMin1.setPreferredSize(new java.awt.Dimension(150, 150));
        panel_matrizMin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_matrizMin1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout panel_matrizMin1Layout = new javax.swing.GroupLayout(panel_matrizMin1);
        panel_matrizMin1.setLayout(panel_matrizMin1Layout);
        panel_matrizMin1Layout.setHorizontalGroup(
            panel_matrizMin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_matrizMin1Layout.setVerticalGroup(
            panel_matrizMin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        panel_matrizMin3.setPreferredSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout panel_matrizMin3Layout = new javax.swing.GroupLayout(panel_matrizMin3);
        panel_matrizMin3.setLayout(panel_matrizMin3Layout);
        panel_matrizMin3Layout.setHorizontalGroup(
            panel_matrizMin3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_matrizMin3Layout.setVerticalGroup(
            panel_matrizMin3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jLabel4.setText("RECUPERADOS MINIMOS");

        panel_matrizMin4.setPreferredSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout panel_matrizMin4Layout = new javax.swing.GroupLayout(panel_matrizMin4);
        panel_matrizMin4.setLayout(panel_matrizMin4Layout);
        panel_matrizMin4Layout.setHorizontalGroup(
            panel_matrizMin4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        panel_matrizMin4Layout.setVerticalGroup(
            panel_matrizMin4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        panel_matrizMin2.setPreferredSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout panel_matrizMin2Layout = new javax.swing.GroupLayout(panel_matrizMin2);
        panel_matrizMin2.setLayout(panel_matrizMin2Layout);
        panel_matrizMin2Layout.setHorizontalGroup(
            panel_matrizMin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_matrizMin2Layout.setVerticalGroup(
            panel_matrizMin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panel_matrizE1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                        .addComponent(panel_matrizE2, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                        .addComponent(panel_matrizE3, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                        .addComponent(panel_matrizE4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(260, 260, 260)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_matrizP1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(panel_matrizP2, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(panel_matrizP3, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_matrizP4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_matrizMax1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(panel_matrizMax2, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(panel_matrizMax3, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_matrizMax4, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_matrizMin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_matrizMin2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_matrizMin3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_matrizMin4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(313, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(10, 10, 10)
                        .addComponent(panel_matrizMin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_matrizMin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panel_matrizMin3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_matrizMin4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(panel_matrizE1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panel_matrizE2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(panel_matrizE3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panel_matrizE4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(panel_matrizP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panel_matrizP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(panel_matrizP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panel_matrizP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(panel_matrizMax1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panel_matrizMax2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(panel_matrizMax3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panel_matrizMax4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panel_matrizE1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_matrizE1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_matrizE1MousePressed

    private void panel_matrizP1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_matrizP1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_matrizP1MousePressed

    private void panel_matrizMax1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_matrizMax1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_matrizMax1MousePressed

    private void panel_matrizMin1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_matrizMin1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_matrizMin1MousePressed
    public void asignar(JPanel asignado){
        JLabel[][] pixels = new JLabel[filas][columnas];
        for (int i = 0; i < filas; i++) {
            for (int j = 0; j < columnas; j++) {
                pixels[i][j] = new JLabel();
                pixels[i][j].setOpaque(true);
                pixels[i][j].setBackground(Color.WHITE);

                // Agregamos un MouseListener para cambiar el color al mantener presionado el botón del mouse
                final int row = i;
                final int col = j;
                pixels[i][j].addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        if(pixels[row][col].getBackground().toString().equals(Color.WHITE.toString())){
                            pixels[row][col].setBackground(Color.BLACK);
                        }else{
                            pixels[row][col].setBackground(Color.WHITE);
                        }
                      
                        
                    }
                });

                asignado.add(pixels[i][j]);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel_matrizE1;
    private javax.swing.JPanel panel_matrizE2;
    private javax.swing.JPanel panel_matrizE3;
    private javax.swing.JPanel panel_matrizE4;
    private javax.swing.JPanel panel_matrizMax1;
    private javax.swing.JPanel panel_matrizMax2;
    private javax.swing.JPanel panel_matrizMax3;
    private javax.swing.JPanel panel_matrizMax4;
    private javax.swing.JPanel panel_matrizMin1;
    private javax.swing.JPanel panel_matrizMin2;
    private javax.swing.JPanel panel_matrizMin3;
    private javax.swing.JPanel panel_matrizMin4;
    private javax.swing.JPanel panel_matrizP1;
    private javax.swing.JPanel panel_matrizP2;
    private javax.swing.JPanel panel_matrizP3;
    private javax.swing.JPanel panel_matrizP4;
    // End of variables declaration//GEN-END:variables
}
class MatrizPanel extends JPanel {
    private int numRows;
    private int numCols;
    private boolean[][] grid; // Matriz para almacenar el estado de cada celda

    public MatrizPanel(int numRows, int numCols) {
        this.numRows = numRows;
        this.numCols = numCols;
        this.grid = new boolean[numRows][numCols];

        // Agregar un MouseListener para manejar los clics del ratón
        addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int cellSize = getWidth() / numCols;
                int row = e.getY() / cellSize;
                int col = e.getX() / cellSize;
                grid[row][col] = !grid[row][col]; // Alternar entre negro y blanco
                repaint(); // Volver a dibujar el panel
            }
        });
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        int cellSize = getWidth() / numCols;

        for (int row = 0; row < numRows; row++) {
            for (int col = 0; col < numCols; col++) {
                if (grid[row][col]) {
                    g.setColor(Color.BLACK);
                } else {
                    g.setColor(Color.WHITE);
                }
                g.fillRect(col * cellSize, row * cellSize, cellSize, cellSize);
            }
        }
    }
}

